import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Hesham Ali | Portfolio",
  description: "Welcome to my full stack Next.js 14 space portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Hesham Ali",
    url: "https://github.com/Hesham000",
  },
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/icon2.png", type: "image/png", sizes: "16x16" },
    ],
    apple: "/logo.png",
    shortcut: "/favicon.ico",
  },
  manifest: "/manifest.json",
} as const;
